# Generated by Django 4.2.6 on 2023-10-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_validity_from", models.DateTimeField()),
                ("slot_validity_till", models.DateTimeField()),
                ("description", models.TextField()),
                ("repeat_days", models.JSONField()),
                ("assignments", models.ManyToManyField(to="organizer.assignment")),
            ],
        ),
    ]
