# Generated by Django 4.2.6 on 2023-10-22 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="description",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="assignments",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="repeat_days",
        ),
        migrations.AddField(
            model_name="appointment",
            name="end_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 0, 0)),
        ),
        migrations.AddField(
            model_name="appointment",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 0, 0)),
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
    ]
